services:
  app:
    container_name: app
    image: ${APP_IMAGE}:${APP_IMAGE_TAG}
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - ${APP_PORT}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - recommendations-db
    command: ./entrypoint.sh
    volumes:
      - .:/app

  recommendations-db:
    container_name: recommendations-db
    image: ${PG_IMAGE}:${PG_IMAGE_TAG}
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:${PG_PORT}

volumes:
  pgdata:
